name: Build & Deploy (Production)

on:
  push:
    branches:
      - release
    paths:
      - 'packages/api/**'
      # - 'packages/another-package/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Deploy
        run: echo "Deployed"
